services:
  md-to-pdf:
    image: dalibo/pandocker:latest
    volumes:
      - ./:/pandoc
    working_dir: /pandoc
    command: ["input.md", "-o", "output.pdf", "--template=template.tex", "--pdf-engine=xelatex"]
