services:
  md-to-pdf:
    image: pandoc/latex:latest
    volumes:
      - ./:/data
    working_dir: /data
    command: ["${INPUT_FILE}", "-o", "${OUTPUT_FILE}", "--template=template.tex", "--pdf-engine=xelatex", "--variable=linkcolor:blue"]
